update

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,6 +1,25 @@
 #!/bin/sh
 
-DOTFILES_REPO_URL="git@github.com:tifandotme/dotfiles.git"
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
 
-echo "Updating the yadm repo origin URL"
-yadm remote set-url origin "$DOTFILES_REPO_URL"
+set -eu
+
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+  echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+  exit 1
+fi
+
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+  if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+    if ! "$bootstrap"; then
+      echo "Error: bootstrap '$bootstrap' failed" >&2
+      exit 1
+    fi
+  fi
+done
+
